

services:
  mongodb:
    image: mongo:7-jammy
    container_name: guestbook-db
    volumes:
      - mongo_data:/data/db
    networks:
      backend-network: {}
      

  api:
    build: ./backend
    container_name: guestbook-api
    environment:
      - MONGO_URL=mongodb://mongodb:27017
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      frontend-network: {}
      backend-network: {}


  web:
    build: ./frontend
    container_name: guestbook-web
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      frontend-network: {}


networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

volumes:
  mongo_data:
